package orm;
// Generated Dec 2, 2017 12:13:47 AM by Hibernate Tools 4.3.1

import javax.persistence.GeneratedValue;
import javax.persistence.Id;




/**
 * Assignment generated by hbm2java
 */
public class Assignment  implements java.io.Serializable {

//@Id @GeneratedValue
     private int assignmentId;
     private int courseId;
     private String assignmentName;
     private String assignmentDescription;
     private Integer assignmentTypeId;
     private int isGraded;
     private Integer potentialScore;

    public Assignment() {
    }

	
    public Assignment(int assignmentId, int courseId, String assignmentName, int isGraded) {
        this.assignmentId = assignmentId;
        this.courseId = courseId;
        this.assignmentName = assignmentName;
        this.isGraded = isGraded;
    }
    public Assignment(int assignmentId, int courseId, String assignmentName, String assignmentDescription, Integer assignmentTypeId, int isGraded, Integer potentialScore) {
       this.assignmentId = assignmentId;
       this.courseId = courseId;
       this.assignmentName = assignmentName;
       this.assignmentDescription = assignmentDescription;
       this.assignmentTypeId = assignmentTypeId;
       this.isGraded = isGraded;
       this.potentialScore = potentialScore;
    }
   
    public int getAssignmentId() {
        return this.assignmentId;
    }
    
    public void setAssignmentId(int assignmentId) {
        this.assignmentId = assignmentId;
    }
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }
    public String getAssignmentName() {
        return this.assignmentName;
    }
    
    public void setAssignmentName(String assignmentName) {
        this.assignmentName = assignmentName;
    }
    public String getAssignmentDescription() {
        return this.assignmentDescription;
    }
    
    public void setAssignmentDescription(String assignmentDescription) {
        this.assignmentDescription = assignmentDescription;
    }
    public Integer getAssignmentTypeId() {
        return this.assignmentTypeId;
    }
    
    public void setAssignmentTypeId(Integer assignmentTypeId) {
        this.assignmentTypeId = assignmentTypeId;
    }
    public int getIsGraded() {
        return this.isGraded;
    }
    
    public void setIsGraded(int isGraded) {
        this.isGraded = isGraded;
    }
    public Integer getPotentialScore() {
        return this.potentialScore;
    }
    
    public void setPotentialScore(Integer potentialScore) {
        this.potentialScore = potentialScore;
    }




}


