package orm;
// Generated Dec 2, 2017 12:13:47 AM by Hibernate Tools 4.3.1



/**
 * CourseInstructorId generated by hbm2java
 */
public class CourseInstructorId  implements java.io.Serializable {


     private int courseId;
     private int userId;

    public CourseInstructorId() {
    }

    public CourseInstructorId(int courseId, int userId) {
       this.courseId = courseId;
       this.userId = userId;
    }
   
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CourseInstructorId) ) return false;
		 CourseInstructorId castOther = ( CourseInstructorId ) other; 
         
		 return (this.getCourseId()==castOther.getCourseId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCourseId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


