package orm;
// Generated Dec 2, 2017 12:13:47 AM by Hibernate Tools 4.3.1



/**
 * UserCourseId generated by hbm2java
 */
public class UserCourseId  implements java.io.Serializable {


     private int userId;
     private int courseId;

    public UserCourseId() {
    }

    public UserCourseId(int userId, int courseId) {
       this.userId = userId;
       this.courseId = courseId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserCourseId) ) return false;
		 UserCourseId castOther = ( UserCourseId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getCourseId()==castOther.getCourseId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getCourseId();
         return result;
   }   


}


