package orm;
// Generated Dec 2, 2017 12:13:47 AM by Hibernate Tools 4.3.1



/**
 * UserAssignmentId generated by hbm2java
 */
public class UserAssignmentId  implements java.io.Serializable {


     private int assignmentId;
     private int userId;

    public UserAssignmentId() {
    }

    public UserAssignmentId(int assignmentId, int userId) {
       this.assignmentId = assignmentId;
       this.userId = userId;
    }
   
    public int getAssignmentId() {
        return this.assignmentId;
    }
    
    public void setAssignmentId(int assignmentId) {
        this.assignmentId = assignmentId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserAssignmentId) ) return false;
		 UserAssignmentId castOther = ( UserAssignmentId ) other; 
         
		 return (this.getAssignmentId()==castOther.getAssignmentId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAssignmentId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


