INSERT INTO LMS.USER_ROLE (USER_ROLE_NAME) 
	VALUES ('student');
INSERT INTO LMS.USER_ROLE (USER_ROLE_NAME) 
	VALUES ('professor');

INSERT INTO LMS.COURSE (COURSE_NAME, SEMESTER) 
	VALUES ('CT406', 'fall2017');


INSERT INTO LMS.T_USER (USER_NAME, EMAIL, PASSWORD, ROLE_ID) 
	VALUES ('cap', 'cap@cap.com', 'cap', 1);
INSERT INTO LMS.T_USER (USER_NAME, EMAIL, PASSWORD, ROLE_ID) 
	VALUES ('pro', 'pro@pro.com', 'pro', 2);

INSERT INTO LMS.COURSE_INSTRUCTOR (COURSE_ID, USER_ID) 
	VALUES (1, 2);

INSERT INTO LMS.USER_COURSE (USER_ID, COURSE_ID) 
	VALUES (1, 1);

INSERT INTO LMS.ASSIGNMENT_TYPE (COURSE_ID, ASSIGNMENT_TYPE_NAME) 
	VALUES (1, 'ClassWork');
INSERT INTO LMS.ASSIGNMENT_TYPE (COURSE_ID, ASSIGNMENT_TYPE_NAME) 
	VALUES (1, 'quizes');

INSERT INTO LMS."ASSIGNMENT" (COURSE_ID, ASSIGNMENT_NAME, ASSIGNMENT_DESCRIPTION, ASSIGNMENT_TYPE_ID, IS_GRADED, POTENTIAL_SCORE) 
	VALUES (1, 'Lab 12/12', 'create and test a car object', 1, 0, 50);
INSERT INTO LMS."ASSIGNMENT" (COURSE_ID, ASSIGNMENT_NAME, ASSIGNMENT_DESCRIPTION, ASSIGNMENT_TYPE_ID, IS_GRADED, POTENTIAL_SCORE) 
	VALUES (1, 'Networking', 'pass data using json and xml', 1, 0, 40);
INSERT INTO LMS."ASSIGNMENT" (COURSE_ID, ASSIGNMENT_NAME, ASSIGNMENT_DESCRIPTION, ASSIGNMENT_TYPE_ID, IS_GRADED, POTENTIAL_SCORE) 
	VALUES (1, 'JSF', 'create a LMS using JSF', 1, 0, 500);
INSERT INTO LMS."ASSIGNMENT" (COURSE_ID, ASSIGNMENT_NAME, ASSIGNMENT_DESCRIPTION, ASSIGNMENT_TYPE_ID, IS_GRADED, POTENTIAL_SCORE) 
	VALUES (1, 'JSF2', 'create a LMS using JSF', 1, 0, 400);
INSERT INTO LMS."ASSIGNMENT" (COURSE_ID, ASSIGNMENT_NAME, ASSIGNMENT_DESCRIPTION, ASSIGNMENT_TYPE_ID, IS_GRADED, POTENTIAL_SCORE) 
	VALUES (1, 'JSF3', 'create a LMS using JSF', 1, 0, 400);








