package hiber;
// Generated Dec 2, 2017 12:13:47 AM by Hibernate Tools 4.3.1



/**
 * AssignmentType generated by hbm2java
 */
public class AssignmentType  implements java.io.Serializable {


     private int assignmentTypeId;
     private int courseId;
     private String assignmentTypeName;

    public AssignmentType() {
    }

    public AssignmentType(int assignmentTypeId, int courseId, String assignmentTypeName) {
       this.assignmentTypeId = assignmentTypeId;
       this.courseId = courseId;
       this.assignmentTypeName = assignmentTypeName;
    }
   
    public int getAssignmentTypeId() {
        return this.assignmentTypeId;
    }
    
    public void setAssignmentTypeId(int assignmentTypeId) {
        this.assignmentTypeId = assignmentTypeId;
    }
    public int getCourseId() {
        return this.courseId;
    }
    
    public void setCourseId(int courseId) {
        this.courseId = courseId;
    }
    public String getAssignmentTypeName() {
        return this.assignmentTypeName;
    }
    
    public void setAssignmentTypeName(String assignmentTypeName) {
        this.assignmentTypeName = assignmentTypeName;
    }




}


