package hiber;
// Generated Dec 2, 2017 12:13:47 AM by Hibernate Tools 4.3.1



/**
 * CourseInstructor generated by hbm2java
 */
public class CourseInstructor  implements java.io.Serializable {


     private CourseInstructorId id;

    public CourseInstructor() {
    }

    public CourseInstructor(CourseInstructorId id) {
       this.id = id;
    }
   
    public CourseInstructorId getId() {
        return this.id;
    }
    
    public void setId(CourseInstructorId id) {
        this.id = id;
    }




}


