package hiber;
// Generated Dec 2, 2017 12:13:47 AM by Hibernate Tools 4.3.1



/**
 * TUser generated by hbm2java
 */
public class TUser  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String email;
     private String password;
     private int roleId;

    public TUser() {
    }

    public TUser(int userId, String userName, String email, String password, int roleId) {
       this.userId = userId;
       this.userName = userName;
       this.email = email;
       this.password = password;
       this.roleId = roleId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }




}


