package hiber;
// Generated Dec 2, 2017 12:13:47 AM by Hibernate Tools 4.3.1



/**
 * UserCourse generated by hbm2java
 */
public class UserCourse  implements java.io.Serializable {


     private UserCourseId id;

    public UserCourse() {
    }

    public UserCourse(UserCourseId id) {
       this.id = id;
    }
   
    public UserCourseId getId() {
        return this.id;
    }
    
    public void setId(UserCourseId id) {
        this.id = id;
    }




}


